version: 1.0

phases:
  build:
    commands:
      - echo Entered the build phase....
      - mvn clean package
  post-build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/department-service.jar
  discard-paths: yes
